# Generated by Django 5.1.4 on 2025-03-02 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('page_count', models.IntegerField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('NP', 'Nepali'), ('JP', 'Japanese'), ('HI', 'HINDI')], default='EN', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
